namespace: default
deployment:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  image: gitlab.praktikum-services.ru:5050/std-014-16/momo-store/momo-frontend
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "800m"
  containerPort: 8080
  imagePullSecrets:
    name: docker-config-secret-front

ingress:
  ingressClassName: "nginx"
  host: momo.netvl.ru
  tlssecretname: tls-secret
  http:
    path: /
    pathType: Prefix
  port:
    number: 8080

service:
  type: ClusterIP
  port: 8080
  protocol: TCP
  targetPort: 8080

configmap:
  include: /etc/nginx/mime.types
  default_type: application/octet-stream
  log_format: main
  log_property: $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for";
  access_log: /var/log/nginx/access.log
  sendfile: "on"
  keepalive_timeout: 65
  listen: 8080
  root: /usr/share/nginx/html
  index: index.html
  try_files: $uri $uri/ /index.html
  proxy_pass: http://backend:8081