---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace | quote }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  tls:
    - hosts: 
      - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlssecretname }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: {{ .Values.ingress.http.path }}
        pathType: {{ .Values.ingress.http.pathType }}
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: {{ .Values.ingress.port.number }}