---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ .Chart.Name }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updatePolicy.updateMode }}
  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Values.vpa.resourcePolicy.containerPolicies.containerName | quote }}
        minAllowed:
{{ toYaml .Values.vpa.minAllowed | indent 10 }}
        maxAllowed:
{{ toYaml .Values.vpa.maxAllowed | indent 10 }}
        controlledResources: {{ .Values.vpa.controlledResources }}
        controlledValues: {{ .Values.vpa.controlledValues }}
